name: "XGBoost A100 Configuration"
description: "High-performance config for A100 GPU"
version: "1.0.0"

model:
  type: "xgboost"
  params:
    max_depth: 10
    learning_rate: 0.05
    n_estimators: 500
    min_child_weight: 3
    subsample: 0.85
    colsample_bytree: 0.85
    objective: "reg:squarederror"
    random_state: 42
    tree_method: "hist"
    device: "cuda:0"
    max_bin: 512